apiVersion: v1
kind: Service
metadata:
  name: availability
  labels:
      app: availability
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: availability