apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
      app: payment
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: payment