apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
      app: recommendation
spec:
  type: LoadBalancer
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: recommendation